constant:
  jwt-const:
    access-token-expiry: 600_000 #10분 (MS)

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost/jwt
    username: root
    password: green502
